=== pmbstyle/L2Solo/data/Npcs/.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "selfId": {
                "type": "integer"
            },
            "template": {
                "type": "object",
                "properties": {
                    "displayId": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "kind": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "level": {
                        "type": "integer"
                    },
                    "hostile": {
                        "type": "boolean"
                    },
                    "raidBoss": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "kind",
                    "name",
                    "title",
                    "level",
                    "hostile"
                ]
            },
            "base": {
                "type": "object",
                "properties": {
                    "str": {
                        "type": "integer"
                    },
                    "dex": {
                        "type": "integer"
                    },
                    "con": {
                        "type": "integer"
                    },
                    "int": {
                        "type": "integer"
                    },
                    "wit": {
                        "type": "integer"
                    },
                    "men": {
                        "type": "integer"
                    }
                },
                "required": [
                    "str",
                    "dex",
                    "con",
                    "int",
                    "wit",
                    "men"
                ]
            },
            "stats": {
                "type": "object",
                "properties": {
                    "pAtk": {
                        "type": "number"
                    },
                    "pAtkRnd": {
                        "type": "integer"
                    },
                    "pDef": {
                        "type": "number"
                    },
                    "mAtk": {
                        "type": "number"
                    },
                    "mDef": {
                        "type": "number"
                    },
                    "accur": {
                        "type": "number"
                    },
                    "atkSpd": {
                        "type": "integer"
                    },
                    "castSpd": {
                        "type": "integer"
                    },
                    "atkRadius": {
                        "type": "integer"
                    }
                },
                "required": [
                    "pAtk",
                    "pAtkRnd",
                    "pDef",
                    "mAtk",
                    "mDef",
                    "accur",
                    "atkSpd",
                    "castSpd",
                    "atkRadius"
                ]
            },
            "speed": {
                "type": "object",
                "properties": {
                    "walk": {
                        "type": "integer"
                    },
                    "run": {
                        "type": "integer"
                    }
                },
                "required": [
                    "walk",
                    "run"
                ]
            },
            "vitals": {
                "type": "object",
                "properties": {
                    "maxHp": {
                        "type": "number"
                    },
                    "maxMp": {
                        "type": "number"
                    },
                    "revHp": {
                        "type": "number"
                    },
                    "revMp": {
                        "type": "number"
                    },
                    "corpseTime": {
                        "type": "integer"
                    }
                },
                "required": [
                    "maxHp",
                    "maxMp",
                    "revHp",
                    "revMp",
                    "corpseTime"
                ]
            },
            "collision": {
                "type": "object",
                "properties": {
                    "radius": {
                        "type": "number"
                    },
                    "size": {
                        "type": "number"
                    }
                },
                "required": [
                    "radius",
                    "size"
                ]
            },
            "equipment": {
                "type": "object",
                "properties": {
                    "weapon": {
                        "type": "integer"
                    },
                    "shield": {
                        "type": "integer"
                    },
                    "reuseTime": {
                        "type": "integer"
                    }
                },
                "required": [
                    "weapon",
                    "shield",
                    "reuseTime"
                ]
            },
            "clan": {
                "type": "object",
                "properties": {
                    "clanName": {
                        "type": "string"
                    },
                    "helpRadius": {
                        "type": "integer"
                    }
                },
                "required": [
                    "clanName",
                    "helpRadius"
                ]
            },
            "rewards": {
                "type": "object",
                "properties": {
                    "exp": {
                        "type": "number"
                    },
                    "sp": {
                        "type": "integer"
                    }
                },
                "required": [
                    "exp",
                    "sp"
                ]
            }
        },
        "required": [
            "selfId",
            "template",
            "base",
            "stats",
            "speed",
            "vitals",
            "collision",
            "equipment",
            "clan",
            "rewards"
        ]
    }
}

=== pmbstyle/L2Solo/data/Npcs/c4_goddard_rune.json
[
  {
    "selfId": 7990,
    "template": {
      "kind": "Npc",
      "name": "Lottery Ticket Seller",
      "title": "",
      "level": 70,
      "hostile": false
    },
    "base": {
      "str": 40,
      "con": 43,
      "dex": 30,
      "int": 21,
      "wit": 20,
      "men": 10
    },
    "stats": {
      "pAtk": 1314,
      "pAtkRnd": 30,
      "pDef": 470,
      "mAtk": 780,
      "mDef": 382,
      "atkSpd": 278,
      "castSpd": 253,
      "atkRadius": 40,
      "accur": 4.75
    },
    "speed": {
      "walk": 55,
      "run": 132
    },
    "vitals": {
      "maxHp": 3862,
      "maxMp": 1493,
      "revHp": 11.85,
      "revMp": 2.78,
      "corpseTime": 7000
    },
    "collision": {
      "radius": 8,
      "size": 23
    },
    "equipment": {
      "weapon": 0,
      "shield": 0,
      "reuseTime": 0
    },
    "clan": {
      "clanName": "",
      "helpRadius": 0
    },
    "rewards": {
      "exp": 0,
      "sp": 0
    }
  },
  {
    "selfId": 8092,
    "template": {
      "kind": "SignsPriest",
      "name": "Black Marketeer of Mammon",
      "title": "",
      "level": 70,
      "hostile": false
    },
    "base": {
      "str": 40,
      "con": 43,
      "dex": 30,
      "int": 21,
      "wit": 20,
      "men": 10
    },
    "stats": {
      "pAtk": 1314,
      "pAtkRnd": 30,
      "pDef": 470,
      "mAtk": 780,
      "mDef": 382,
      "atkSpd": 278,
      "castSpd": 253,
      "atkRadius": 40,
      "accur": 4.75
    },
    "speed": {
      "walk": 55,
      "run": 132
    },
    "vitals": {
      "maxHp": 3862,
      "maxMp": 1493,
      "revHp": 11.85,
      "revMp": 2.78,
      "corpseTime": 7000
    },
    "collision": {
      "radius": 8,
      "size": 18
    },
    "equipment": {
      "weapon": 0,
      "shield": 0,
      "reuseTime": 0
    },
    "clan": {
      "clanName": "",
      "helpRadius": 0
    },
    "rewards": {
      "exp": 0,
      "sp": 0
    }
  },
  {
    "selfId": 8257,
    "template": {
      "kind": "Merchant",
      "name": "Veronica",
      "title": "Trader",
      "level": 70,
      "hostile": false
    },
    "base": {
      "str": 40,
      "con": 43,
      "dex": 30,
      "int": 21,
      "wit": 20,
      "men": 10
    },
    "stats": {
      "pAtk": 1314,
      "pAtkRnd": 30,
      "pDef": 470,
      "mAtk": 780,
      "mDef": 382,
      "atkSpd": 278,
      "castSpd": 253,
      "atkRadius": 40,
      "accur": 4.75
    },
    "speed": {
      "walk": 55,
      "run": 132
    },
    "vitals": {
      "maxHp": 3862,
      "maxMp": 1493,
      "revHp": 11.85,
      "revMp": 2.78,
      "corpseTime": 7000
    },
    "collision": {
      "radius": 8,
      "size": 25.3
    },
    "equipment": {
      "weapon": 0,
      "shield": 0,
      "reuseTime": 0
    },
    "clan": {
      "clanName": "",
      "helpRadius": 0
    },
    "rewards": {
      "exp": 0,
      "sp": 0
    }
  },
  {
    "selfId": 8258,
    "template": {
      "kind": "Merchant",
      "name": "Helmut",
      "title": "Trader",
      "level": 70,
      "hostile": false
    },
    "base": {
      "str": 40,
      "con": 43,
      "dex": 30,
      "int": 21,
      "wit": 20,
      "men": 10
    },
    "stats": {
      "pAtk": 1314,
      "pAtkRnd": 30,
      "pDef": 470,
      "mAtk": 780,
      "mDef": 382,
      "atkSpd": 278,
      "castSpd": 253,
      "atkRadius": 40,
      "accur": 4.75
    },
    "speed": {
      "walk": 55,
      "run": 132
    },
    "vitals": {
      "maxHp": 3862,
      "maxMp": 1493,
      "revHp": 11.85,
      "revMp": 2.78,
      "corpseTime": 7000
    },
    "collision": {
      "radius": 10,
      "size": 24
    },
    "equipment": {
      "weapon": 0,
      "shield": 0,
      "reuseTime": 0
    },
    "clan": {
      "clanName": "",
      "helpRadius": 0
    },
    "rewards": {
      "exp": 0,
      "sp": 0
    }
  },
  {
    "selfId": 8259,
    "template": {
      "kind": "Merchant",
      "name": "Janne",
      "title": "Trader",
      "level": 70,
      "hostile": false
    },
    "base": {
      "str": 40,
      "con": 43,
      "dex": 30,
      "int": 21,
      "wit": 20,
      "men": 10
    },
    "stats": {
      "pAtk": 1314,
      "pAtkRnd": 30,
      "pDef": 470,
      "mAtk": 780,
      "mDef": 382,
      "atkSpd": 278,
      "castSpd": 253,
      "atkRadius": 40,
      "accur": 4.75
    },
    "speed": {
      "walk": 55,
      "run": 132
    },
    "vitals": {
      "maxHp": 3862,
      "maxMp": 1493,
      "revHp": 11.85,
      "revMp": 2.78,
      "corpseTime": 7000
    },
    "collision": {
      "radius": 8,
      "size": 22.5
    },
    "equipment": {
      "weapon": 0,
      "shield": 0,
      "reuseTime": 0
    },
    "clan": {
      "clanName": "",
      "helpRadius": 0
    },
    "rewards": {
      "exp": 0,
      "sp": 0
    }
  },
  {
    "selfId": 8260,
    "template": {
      "kind": "Merchant",
      "name": "Judith",
      "title": "Trader",
      "level": 70,
      "hostile": false
    },
    "base": {
      "str": 40,
      "con": 43,
      "dex": 30,
      "int": 21,
      "wit": 20,
      "men": 10
    },
    "stats": {
      "pAtk": 1314,
      "pAtkRnd": 30,
      "pDef": 470,
      "mAtk": 780,
      "mDef": 382,
      "atkSpd": 278,
      "castSpd": 253,
      "atkRadius": 40,
      "accur": 4.75
    },
    "speed": {
      "walk": 55,
      "run": 132
    },
    "vitals": {
      "maxHp": 3862,
      "maxMp": 1493,
      "revHp": 11.85,
      "revMp": 2.78,
      "corpseTime": 7000
    },
    "collision": {
      "radius": 8,
      "size": 25.3
    },
    "equipment": {
      "weapon": 0,
      "shield": 0,
      "reuseTime": 0
    },
    "clan": {
      "clanName": "",
      "helpRadius": 0
    },
    "rewards": {
      "exp": 0,
      "sp": 0
    }
  },
  {
    "selfId": 8261,
    "template": {
      "kind": "Merchant",
      "name": "Renee",
      "title": "Trader",
      "level": 70,
      "hostile": false
    },
    "base": {
      "str": 40,
      "con": 43,
      "dex": 30,
      "int": 21,
      "wit": 20,
      "men": 10
    },
    "stats": {
      "pAtk": 1314,
      "pAtkRnd": 30,
      "pDef": 470,
      "mAtk": 780,
      "mDef": 382,
      "atkSpd": 278,
      "castSpd": 253,
      "atkRadius": 40,
      "accur": 4.75
    },
    "speed": {
      "walk": 55,
      "run": 132
    },
    "vitals": {
      "maxHp": 3862,
      "maxMp": 1493,
      "revHp": 11.85,
      "revMp": 2.78,
      "corpseTime": 7000
    },
    "collision": {
      "radius": 7,
      "size": 18
    },
    "equipment": {
      "weapon": 0,
      "shield": 0,
      "reuseTime": 0
    },
    "clan": {
      "clanName": "",
      "helpRadius": 0
    },
    "rewards": {
      "exp": 0,
      "sp": 0
    }
  },
  {
    "selfId": 8262,
    "template": {
      "kind": "Merchant",
      "name": "Rupert",
      "title": "Trader",
      "level": 70,
      "hostile": false
    },
    "base": {
      "str": 40,
      "con": 43,
      "dex": 30,
      "int": 21,
      "wit": 20,
      "men": 10
    },
    "stats": {
      "pAtk": 1314,
      "pAtkRnd": 30,
      "pDef": 470,
      "mAtk": 780,
      "mDef": 382,
      "atkSpd": 278,
      "castSpd": 253,
      "atkRadius": 40,
      "accur": 4.75
    },
    "speed": {
      "walk": 55,
      "run": 132
    },
    "vitals": {
      "maxHp": 3862,
      "maxMp": 1493,
      "revHp": 11.85,
      "revMp": 2.78,
      "corpseTime": 7000
    },
    "collision": {
      "radius": 8,
      "size": 25.3
    },
    "equipment": {
      "weapon": 0,
      "shield": 0,
      "reuseTime": 0
    },
    "clan": {
      "clanName": "",
      "helpRadius": 0
    },
    "rewards": {
      "exp": 0,
      "sp": 0
    }
  },
  {
    "selfId": 8263,
    "template": {
      "kind": "Merchant",
      "name": "Liesel",
      "title": "Trader",
      "level": 70,
      "hostile": false
    },
    "base": {
      "str": 40,
      "con": 43,
      "dex": 30,
      "int": 21,
      "wit": 20,
      "men": 10
    },
    "stats": {
      "pAtk": 1314,
      "pAtkRnd": 30,
      "pDef": 470,
      "mAtk": 780,
      "mDef": 382,
      "atkSpd": 278,
      "castSpd": 253,
      "atkRadius": 40,
      "accur": 4.75
    },
    "speed": {
      "walk": 55,
      "run": 132
    },
    "vitals": {
      "maxHp": 3862,
      "maxMp": 1493,
      "revHp": 11.85,
      "revMp": 2.78,
      "corpseTime": 7000
    },
    "collision": {
      "radius": 8,
      "size": 22.5
    },
    "equipment": {
      "weapon": 0,
      "shield": 0,
      "reuseTime": 0
    },
    "clan": {
      "clanName": "",
      "helpRadius": 0
    },
    "rewards": {
      "exp": 0,
      "sp": 0
    }
  },
  {
    "selfId": 8264,
    "template": {
      "kind": "SymbolMaker",
      "name": "Olsun",
      "title": "Symbol Maker",
      "level": 70,
      "hostile": false
    },
    "base": {
      "str": 40,
      "con": 43,
      "dex": 30,
      "int": 21,
      "wit": 20,
      "men": 10
    },
    "stats": {
      "pAtk": 1314,
      "pAtkRnd": 30,
      "pDef": 470,
      "mAtk": 780,
      "mDef": 382,
      "atkSpd": 278,
      "castSpd": 253,
      "atkRadius": 40,
      "accur": 4.75
    },
    "speed": {
      "walk": 55,
      "run": 132
    },
    "vitals": {
      "maxHp": 3862,
      "maxMp": 1493,
      "revHp": 11.85,
      "revMp": 2.78,
      "corpseTime": 7000
    },
    "collision": {
      "radius": 8,
      "size": 23
    },
    "equipment": {
      "weapon": 0,
      "shield": 0,
      "reuseTime": 0
    },
    "clan": {
      "clanName": "",
      "helpRadius": 0
    },
    "rewards": {
      "exp": 0,
      "sp": 0
    }
  },
  {
    "selfId": 8265,
    "template": {
      "kind": "Merchant",
      "name": "Annette",
      "title": "Pet Manager",
      "level": 70,
      "hostile": false
    },
    "base": {
      "str": 40,
      "con": 43,
      "dex": 30,
      "int": 21,
      "wit": 20,
      "men": 10
    },
    "stats": {
      "pAtk": 1314,
      "pAtkRnd": 30,
      "pDef": 470,
      "mAtk": 780,
      "mDef": 382,
