=== pmbstyle/L2Solo/data/Items/Weapons/.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "selfId": {
                "type": "integer"
            },
            "template": {
                "type": "object",
                "properties": {
                    "kind": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "class1": {
                        "type": "integer"
                    },
                    "class2": {
                        "type": "integer"
                    },
                    "mass": {
                        "type": "integer"
                    },
                    "price": {
                        "type": "integer"
                    }
                },
                "required": [
                    "kind",
                    "name",
                    "class1",
                    "class2",
                    "mass",
                    "price"
                ]
            },
            "stats": {
                "type": "object",
                "properties": {
                    "pAtk": {
                        "type": "integer"
                    },
                    "pAtkRnd": {
                        "type": "integer"
                    },
                    "mAtk": {
                        "type": "integer"
                    },
                    "atkSpd": {
                        "type": "integer"
                    },
                    "crit": {
                        "type": "integer"
                    },
                    "accur": {
                        "type": "number"
                    },
                    "attackRange": {
                        "type": "integer"
                    }
                },
                "required": [
                    "pAtk",
                    "pAtkRnd",
                    "mAtk",
                    "atkSpd",
                    "crit",
                    "accur"
                ]
            },
            "etc": {
                "type": "object",
                "properties": {
                    "slot": {
                        "type": "integer"
                    },
                    "mp": {
                        "type": "integer"
                    },
                    "soulshot": {
                        "type": "integer"
                    },
                    "spiritshot": {
                        "type": "integer"
                    },
                    "rank": {
                        "type": "string"
                    },
                    "cristals": {
                        "type": "integer"
                    }
                },
                "required": [
                    "slot",
                    "mp",
                    "soulshot",
                    "spiritshot",
                    "rank",
                    "cristals"
                ]
            }
        },
        "required": [
            "selfId",
            "template",
            "stats",
            "etc"
        ]
    }
}

=== pmbstyle/L2Solo/data/Items/Weapons/c4_raid_bosses.json
[
  {
    "selfId": 5286,
    "template": {
      "name": "Berserker Blade",
      "class1": 0,
      "class2": 0,
      "mass": 1380,
      "price": 6130000,
      "kind": "Weapon.GreatSword"
    },
    "stats": {
      "pAtk": 190,
      "pAtkRnd": 10,
      "mAtk": 83,
      "atkSpd": 325,
      "crit": 80,
      "accur": 0
    },
    "etc": {
      "slot": 14,
      "mp": 0,
      "soulshot": 3,
      "spiritshot": 3,
      "rank": "c",
      "cristals": 2452
    }
  },
  {
    "selfId": 6365,
    "template": {
      "name": "Basalt Battlehammer",
      "class1": 0,
      "class2": 0,
      "mass": 1570,
      "price": 48800000,
      "kind": "Weapon.Blunt"
    },
    "stats": {
      "pAtk": 281,
      "pAtkRnd": 20,
      "mAtk": 132,
      "atkSpd": 379,
      "crit": 40,
      "accur": 4
    },
    "etc": {
      "slot": 7,
      "mp": 0,
      "soulshot": 1,
      "spiritshot": 1,
      "rank": "s",
      "cristals": 2440
    }
  },
  {
    "selfId": 6369,
    "template": {
      "name": "Dragon Hunter Axe",
      "class1": 0,
      "class2": 0,
      "mass": 1820,
      "price": 48800000,
      "kind": "Weapon.Blunt"
    },
    "stats": {
      "pAtk": 342,
      "pAtkRnd": 20,
      "mAtk": 132,
      "atkSpd": 325,
      "crit": 40,
      "accur": 4
    },
    "etc": {
      "slot": 14,
      "mp": 0,
      "soulshot": 1,
      "spiritshot": 1,
      "rank": "s",
      "cristals": 2440
    }
  }
]

=== pmbstyle/L2Solo/data/Items/Weapons/c4_s_grade.json
[
    {
        "selfId": 6364,
        "template": {
            "name": "Forgotten Blade",
            "class1": 0,
            "class2": 0,
            "mass": 1300,
            "price": 48800000,
            "kind": "Weapon.Sword"
        },
        "stats": {
            "pAtk": 281,
            "pAtkRnd": 10,
            "mAtk": 132,
            "atkSpd": 379,
            "crit": 80,
            "accur": 0
        },
        "etc": {
            "slot": 7,
            "mp": 0,
            "soulshot": 1,
            "spiritshot": 1,
            "rank": "s",
            "cristals": 2440
        }
    },
    {
        "selfId": 6366,
        "template": {
            "name": "Imperial Staff",
            "class1": 0,
            "class2": 0,
            "mass": 910,
            "price": 48800000,
            "kind": "Weapon.Blunt"
        },
        "stats": {
            "pAtk": 274,
            "pAtkRnd": 20,
            "mAtk": 175,
            "atkSpd": 325,
            "crit": 40,
            "accur": 4
        },
        "etc": {
            "slot": 14,
            "mp": 0,
            "soulshot": 1,
            "spiritshot": 1,
            "rank": "s",
            "cristals": 2440
        }
    },
    {
        "selfId": 6367,
        "template": {
            "name": "Angel Slayer",
            "class1": 0,
            "class2": 0,
            "mass": 950,
            "price": 48800000,
            "kind": "Weapon.Knife"
        },
        "stats": {
            "pAtk": 246,
            "pAtkRnd": 5,
            "mAtk": 132,
            "atkSpd": 433,
            "crit": 120,
            "accur": -3
        },
        "etc": {
            "slot": 7,
            "mp": 0,
            "soulshot": 1,
            "spiritshot": 1,
            "rank": "s",
            "cristals": 2440
        }
    },
    {
        "selfId": 6370,
        "template": {
            "name": "Saint Spear",
            "class1": 0,
            "class2": 0,
            "mass": 1800,
            "price": 48800000,
            "kind": "Weapon.Pole"
        },
        "stats": {
            "pAtk": 281,
            "pAtkRnd": 10,
            "mAtk": 132,
            "atkSpd": 325,
            "crit": 80,
            "accur": -3
        },
        "etc": {
            "slot": 14,
            "mp": 0,
            "soulshot": 1,
            "spiritshot": 1,
            "rank": "s",
            "cristals": 2440
        }
    },
    {
        "selfId": 6371,
        "template": {
            "name": "Demon Splinter",
            "class1": 0,
            "class2": 0,
            "mass": 1350,
            "price": 48800000,
            "kind": "Weapon.DualFist"
        },
        "stats": {
            "pAtk": 342,
            "pAtkRnd": 5,
            "mAtk": 132,
            "atkSpd": 325,
            "crit": 40,
            "accur": 4
        },
        "etc": {
            "slot": 14,
            "mp": 0,
            "soulshot": 1,
            "spiritshot": 1,
            "rank": "s",
            "cristals": 2440
        }
    },
    {
        "selfId": 6372,
        "template": {
            "name": "Heaven's Divider",
            "class1": 0,
            "class2": 0,
            "mass": 1380,
            "price": 48800000,
            "kind": "Weapon.GreatSword"
        },
        "stats": {
            "pAtk": 342,
            "pAtkRnd": 10,
            "mAtk": 132,
            "atkSpd": 325,
            "crit": 80,
            "accur": 0
        },
        "etc": {
            "slot": 14,
            "mp": 0,
            "soulshot": 1,
            "spiritshot": 1,
            "rank": "s",
            "cristals": 2440
        }
    },
    {
        "selfId": 6579,
        "template": {
            "name": "Arcana Mace",
            "class1": 0,
            "class2": 0,
            "mass": 1300,
            "price": 48800000,
            "kind": "Weapon.Blunt"
        },
        "stats": {
            "pAtk": 225,
            "pAtkRnd": 20,
            "mAtk": 175,
            "atkSpd": 379,
            "crit": 40,
            "accur": 4
        },
        "etc": {
            "slot": 7,
            "mp": 0,
            "soulshot": 1,
            "spiritshot": 1,
            "rank": "s",
            "cristals": 2440
        }
    },
    {
        "selfId": 6580,
        "template": {
            "name": "Tallum Blade*Dark Legion's Edge",
            "class1": 0,
            "class2": 0,
            "mass": 2080,
            "price": 48800000,
            "kind": "Weapon.Dual"
        },
        "stats": {
            "pAtk": 342,
            "pAtkRnd": 10,
            "mAtk": 132,
            "atkSpd": 325,
            "crit": 80,
            "accur": 0
        },
        "etc": {
            "slot": 14,
            "mp": 0,
            "soulshot": 1,
            "spiritshot": 1,
            "rank": "s",
            "cristals": 2440
        }
    },
    {
        "selfId": 7575,
        "template": {
            "name": "Draconic Bow",
            "class1": 0,
            "class2": 0,
            "mass": 1650,
            "price": 48800000,
            "kind": "Weapon.Bow"
        },
        "stats": {
            "pAtk": 581,
            "pAtkRnd": 5,
            "mAtk": 132,
            "atkSpd": 293,
            "crit": 120,
            "accur": -3
        },
        "etc": {
            "slot": 14,
            "mp": 11,
            "soulshot": 1,
            "spiritshot": 1,
            "rank": "s",
            "cristals": 2440
        }
    }
]

=== pmbstyle/L2Solo/data/Items/Weapons/c4_special_ability_weapons.json
[
    {
        "selfId": 4839,
        "template": { "kind": "Weapon.Pole", "name": "Orcish Glaive - Towering Blow", "class1": 0, "class2": 0, "mass": 2030, "price": 2290000 },
        "stats": { "pAtk": 107, "pAtkRnd": 10, "mAtk": 61, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 80 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 2, "spiritshot": 2, "rank": "c", "cristals": 916 }
    },
    {
        "selfId": 4841,
        "template": { "kind": "Weapon.Pole", "name": "Body Slasher - Towering Blow", "class1": 0, "class2": 0, "mass": 2030, "price": 2290000 },
        "stats": { "pAtk": 107, "pAtkRnd": 10, "mAtk": 61, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 80 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 2, "spiritshot": 2, "rank": "c", "cristals": 916 }
    },
    {
        "selfId": 4842,
        "template": { "kind": "Weapon.Pole", "name": "Body Slasher - Wide Blow", "class1": 0, "class2": 0, "mass": 2030, "price": 2290000 },
        "stats": { "pAtk": 107, "pAtkRnd": 10, "mAtk": 61, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 66 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 2, "spiritshot": 2, "rank": "c", "cristals": 916 }
    },
    {
        "selfId": 4844,
        "template": { "kind": "Weapon.Pole", "name": "Bec de Corbin - Towering Blow", "class1": 0, "class2": 0, "mass": 2020, "price": 2870000 },
        "stats": { "pAtk": 122, "pAtkRnd": 10, "mAtk": 68, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 80 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 2, "spiritshot": 2, "rank": "c", "cristals": 1148 }
    },
    {
        "selfId": 4848,
        "template": { "kind": "Weapon.Pole", "name": "Scorpion - Towering Blow", "class1": 0, "class2": 0, "mass": 1990, "price": 4780000 },
        "stats": { "pAtk": 144, "pAtkRnd": 10, "mAtk": 78, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 80 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 3, "spiritshot": 3, "rank": "c", "cristals": 1912 }
    },
    {
        "selfId": 4850,
        "template": { "kind": "Weapon.Pole", "name": "Widow Maker - Towering Blow", "class1": 0, "class2": 0, "mass": 1980, "price": 4780000 },
        "stats": { "pAtk": 144, "pAtkRnd": 10, "mAtk": 78, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 80 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 3, "spiritshot": 3, "rank": "c", "cristals": 1912 }
    },
    {
        "selfId": 4851,
        "template": { "kind": "Weapon.Pole", "name": "Widow Maker - Wide Blow", "class1": 0, "class2": 0, "mass": 1980, "price": 4780000 },
        "stats": { "pAtk": 144, "pAtkRnd": 10, "mAtk": 78, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 66 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 3, "spiritshot": 3, "rank": "c", "cristals": 1912 }
    },
    {
        "selfId": 4853,
        "template": { "kind": "Weapon.Pole", "name": "Orcish Poleaxe - Towering Blow", "class1": 0, "class2": 0, "mass": 1950, "price": 6130000 },
        "stats": { "pAtk": 156, "pAtkRnd": 10, "mAtk": 83, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 80 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 3, "spiritshot": 3, "rank": "c", "cristals": 2452 }
    },
    {
        "selfId": 4854,
        "template": { "kind": "Weapon.Pole", "name": "Orcish Poleaxe - Wide Blow", "class1": 0, "class2": 0, "mass": 1950, "price": 6130000 },
        "stats": { "pAtk": 156, "pAtkRnd": 10, "mAtk": 83, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 66 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 3, "spiritshot": 3, "rank": "c", "cristals": 2452 }
    },
    {
        "selfId": 4860,
        "template": { "kind": "Weapon.Pole", "name": "Lance - Towering Blow", "class1": 0, "class2": 0, "mass": 1920, "price": 13100000 },
        "stats": { "pAtk": 194, "pAtkRnd": 10, "mAtk": 99, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 80 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 1, "spiritshot": 1, "rank": "b", "cristals": 1746 }
    },
    {
        "selfId": 4862,
        "template": { "kind": "Weapon.Pole", "name": "Halberd - Towering Blow", "class1": 0, "class2": 0, "mass": 1900, "price": 18300000 },
        "stats": { "pAtk": 213, "pAtkRnd": 10, "mAtk": 107, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 80 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 1, "spiritshot": 1, "rank": "a", "cristals": 1464 }
    },
    {
        "selfId": 4863,
        "template": { "kind": "Weapon.Pole", "name": "Halberd - Wide Blow", "class1": 0, "class2": 0, "mass": 1900, "price": 18300000 },
        "stats": { "pAtk": 213, "pAtkRnd": 10, "mAtk": 107, "atkSpd": 325, "crit": 80, "accur": -3, "attackRange": 66 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 1, "spiritshot": 1, "rank": "a", "cristals": 1464 }
    },
    {
        "selfId": 5233,
        "template": { "kind": "Weapon.Dual", "name": "Keshanberk*Keshanberk", "class1": 0, "class2": 0, "mass": 2080, "price": 18300000 },
        "stats": { "pAtk": 259, "pAtkRnd": 10, "mAtk": 107, "atkSpd": 325, "crit": 80, "accur": 0 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 1, "spiritshot": 1, "rank": "a", "cristals": 1464 }
    },
    {
        "selfId": 5704,
        "template": { "kind": "Weapon.Dual", "name": "Keshanberk*Keshanberk", "class1": 0, "class2": 0, "mass": 2080, "price": 18300000 },
        "stats": { "pAtk": 259, "pAtkRnd": 10, "mAtk": 107, "atkSpd": 325, "crit": 80, "accur": 0 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 1, "spiritshot": 1, "rank": "a", "cristals": 1464 }
    },
    {
        "selfId": 5705,
        "template": { "kind": "Weapon.Dual", "name": "Keshanberk*Damascus", "class1": 0, "class2": 0, "mass": 2080, "price": 24100000 },
        "stats": { "pAtk": 275, "pAtkRnd": 10, "mAtk": 112, "atkSpd": 325, "crit": 80, "accur": 0 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 1, "spiritshot": 1, "rank": "a", "cristals": 1928 }
    },
    {
        "selfId": 5706,
        "template": { "kind": "Weapon.Dual", "name": "Damascus*Damascus", "class1": 0, "class2": 0, "mass": 2080, "price": 27000000 },
        "stats": { "pAtk": 282, "pAtkRnd": 10, "mAtk": 114, "atkSpd": 325, "crit": 80, "accur": 0 },
        "etc": { "slot": 14, "mp": 0, "soulshot": 1, "spiritshot": 1, "rank": "a", "cristals": 2160 }
    }
]
